import type { Metadata } from "next";
import { Libre_Caslon_Display } from "next/font/google";
import "./globals.css";
import PrelineScript from "./PrelineScript";
import { Providers } from "./providers";

const libreCaslon = Libre_Caslon_Display({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Add defer attribute to load Alpine.js asynchronously */}
        <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@2"></script>
      </head>
      <body className={libreCaslon.className}>
        <Providers>{children}</Providers>
        <PrelineScript />
      </body>
    </html>
  );
}
